fix: avoid certain checks on macOS

diff --git a/test/test_nodebuilder b/test/test_nodebuilder
--- a/test/test_nodebuilder
+++ b/test/test_nodebuilder
@@ -32,8 +32,6 @@ cat output_stdout.txt
 
 for message in \
   "Detected: running on (Linux|macOS).$" \
-  "Performing a system upgrade... ok.$" \
-  "Checking for dependencies... ok.$" \
   "Checking for Bitcoin Core 26.0... (not )?found.$" \
   "Installing Bitcoin Core... ok.$" \
   "Creating application shortcuts... ok.$" \
@@ -56,6 +54,18 @@ for message in \
     exit 1
   fi
 done
+
+if [ "$(uname -s)" != "Darwin ]; then
+  for message in \
+    "Performing a system upgrade... ok.$" \
+    "Checking for dependencies... ok.$"; do
+    if ! grep -Eq "${message}" output_stdout.txt > /dev/null 2>&1; then
+      printf '%s\n' "FAILURE: Expected message ${message} not found."
+      exit 1
+  fi
+done
+
+fi
 
 for message in \
   "apt-utils 1" \
