fix console output tests for FreeBSD

diff --git a/test/test_nodebuilder b/test/test_nodebuilder
--- a/test/test_nodebuilder
+++ b/test/test_nodebuilder
@@ -202,7 +202,7 @@ if [ -s test_output_stderr.txt ]; then
 fi
 
 for message in \
-  'INFO: Detected: running (Linux|macOS).$' \
+  'INFO: Detected: running (Linux|macOS|FreeBSD).$' \
   'INFO: Checking for internet.$' \
   'INFO: Internet checks passed.$' \
   'INFO: (Failed to find|Found) Bitcoin Core [1-9][0-9]*\.[0-9]+(\.[0-9]+)?.$' \
@@ -243,6 +243,7 @@ for message in \
 done
 
 if [ "${COMPILE_BITCOIN}" = 'true' ] ||
+  [ "${TARGET_KERNEL"} = 'FreeBSD' ] ||
   { [ -f /etc/os-release ] && [ "${TARGET_OPERATING_SYSTEM}" = 'alpine' ]; }; then
   for message in \
     'INFO: Ensuring compile dependencies.$' \
@@ -281,7 +282,16 @@ fi
 if [ "${TARGET_KERNEL}" != 'Darwin' ]; then
   for message in \
     'INFO: Ensuring runtime dependencies.$' \
-    'INFO: Creating application shortcuts.$' \
+    'INFO: Creating application shortcuts.$'; do
+    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+      printf '%s\n' "FAILURE: Expected message ${message} not found."
+      exit 1
+    fi
+  done
+fi
+
+if [ "${TARGET_KERNEL}" = 'Linux' ]; then
+  for message in \
     'Checking system memory... [0-9]+\.[0-9] of [0-9]+\.[0-9] GiB free.$'; do
     if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
       printf '%s\n' "FAILURE: Expected message ${message} not found."
