fix syntax

diff --git a/test/test_nodebuilder b/test/test_nodebuilder
--- a/test/test_nodebuilder
+++ b/test/test_nodebuilder
@@ -291,13 +291,11 @@ if [ "${TARGET_KERNEL}" != 'Darwin' ]; then
 fi
 
 if [ "${TARGET_KERNEL}" = 'Linux' ]; then
-  for message in \
-    'Checking system memory... [0-9]+\.[0-9] of [0-9]+\.[0-9] GiB free.$'; do
-    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
-      printf '%s\n' "FAILURE: Expected message ${message} not found."
-      exit 1
-    fi
-  done
+  message='Checking system memory... [0-9]+\.[0-9] of [0-9]+\.[0-9] GiB free.$'
+  if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+    printf '%s\n' "FAILURE: Expected message ${message} not found."
+    exit 1
+  fi
 fi
 
 printf '%s\n' 'PASS: All console output tests passed.'
