test(functional): add `-c/--compile` option to `test_bitcoin` (#601)

diff --git a/test/test_nodebuilder b/test/test_nodebuilder
--- a/test/test_nodebuilder
+++ b/test/test_nodebuilder
@@ -21,15 +21,49 @@ kill_tail_process() {
   fi
 }
 
+print_usage() {
+  printf '%s\n\n' "Usage: $0 [options]"
+  printf '%s\n' "Options:"
+  printf '%s\n' "-c, --compile           Build Bitcoin from source"
+  printf '%s\n' "-h, --help              Display this help message"
+}
+
+compile_bitcoin="false"
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+  -c | --compile)
+    compile_bitcoin="true"
+    ;;
+  -h | --help)
+    print_usage
+    exit 0
+    ;;
+  *)
+    printf '%s\n%s\n' "Error: '$1' is invalid." "Use -h or --help for available options."
+    exit 1
+    ;;
+  esac
+  shift
+done
+
 [ -f test_output_stdout.txt ] || touch test_output_stdout.txt
 tail -f test_output_stdout.txt &
 tail_pid=$!
 
 trap 'if [ $? -eq 0 ]; then handle_exit; else handle_error; fi' EXIT
 
-nohup /bin/sh -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)" \
-  > test_output_stdout.txt \
-  2> test_output_stderr.txt
+wget https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder
+chmod u+x nodebuilder
+if [ "${compile_bitcoin}" = 'true' ]; then
+  ./nodebuilder --compile \
+    > test_output_stdout.txt \
+    2> test_output_stderr.txt
+else
+  ./nodebuilder \
+    > test_output_stdout.txt \
+    2> test_output_stderr.txt
+fi
 rm nodebuilder
 kill_tail_process
 
@@ -64,19 +98,6 @@ for message in \
   fi
 done
 
-if [ "$(uname -s)" != "Darwin" ]; then
-  for message in \
-    "Performing a system upgrade... ok.$" \
-    "Ensuring (build|runtime) dependencies... ok.$" \
-    "Creating application shortcuts... ok.$" \
-    "Checking the memory on your system... [0-9]+\.[0-9] of [0-9]+\.[0-9] GiB free.$"; do
-    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
-      printf '%s\n' "FAILURE: Expected message ${message} not found."
-      exit 1
-    fi
-  done
-fi
-
 for message in \
   "apt-utils" \
   "libzmq" \
@@ -92,5 +113,52 @@ for message in \
     exit 1
   fi
 done
+
+if [ "${compile_bitcoin}" = "true" ] || [ "$(grep "^ID=" /etc/os-release | cut -d= -f2)" = "alpine" ]; then
+  for message in \
+    "Ensuring compile dependencies... ok.$" \
+    "Downloading Bitcoin source code... ok.$" \
+    "Analyzing hardware configuration... ok.$" \
+    "Configuring the build environment... ok.$" \
+    "Compiling source code, please wait... ok.$"; do
+    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+      printf '%s\n' "FAILURE: Expected message ${message} not found."
+      exit 1
+    fi
+  done
+else
+  for message in \
+    "Downloading Bitcoin Core... ok.$" \
+    "Validating the checksum... ok.$" \
+    "Validating the signatures... [0-9]+ good.$" \
+    "Extracting Bitcoin Core... ok.$" \
+    "Running the unit tests... ok.$" \
+    "Installing Bitcoin Core... ok.$" \
+    "Removing installation files... ok.$"; do
+    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+      printf '%s\n' "FAILURE: Expected message ${message} not found."
+      exit 1
+    fi
+  done
+  # from nodebuilder, gpg_good_signatures_required="7"
+  message="Validating the signatures... [0-6] good.$"
+  if grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+    printf '%s\n' "FAILURE: Unexpected message ${message} found."
+    exit 1
+  fi
+fi
+
+if [ "$(uname -s)" != "Darwin" ]; then
+  for message in \
+    "Performing a system upgrade... ok.$" \
+    "Ensuring runtime dependencies... ok.$" \
+    "Creating application shortcuts... ok.$" \
+    "Checking the memory on your system... [0-9]+\.[0-9] of [0-9]+\.[0-9] GiB free.$"; do
+    if ! grep -Eq "${message}" test_output_stdout.txt > /dev/null 2>&1; then
+      printf '%s\n' "FAILURE: Expected message ${message} not found."
+      exit 1
+    fi
+  done
+fi
 
 printf '%s\n' "PASS: All console output tests passed."
