try: add back in the tail process

diff --git a/test/test_nodebuilder b/test/test_nodebuilder
--- a/test/test_nodebuilder
+++ b/test/test_nodebuilder
@@ -1,10 +1,29 @@
 #!/bin/bash
 
+handle_exit() {
+  if kill -0 "${tail_pid}" > /dev/null 2>&1; then
+    kill "${tail_pid}"
+  fi
+}
+
+handle_error() {
+  handle_exit
+  printf '%s\n' "Test failed."
+}
+
+tail -f output_stdout.txt &
+tail_pid=$!
+
+trap 'if [ $? -eq 0 ]; then handle_exit; else handle_error; fi' EXIT
+
 set -o errexit
 set -o nounset
 set -x
 
 nohup /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)" 2> output_stderr.txt > output_stdout.txt
+kill "${tail_pid}"
+printf '%s\n' "Printing the contents of stdout for debug purposes"
+cat output_stdout.txt
 
 for message in \
   "Detected: running on (Linux|macOS).$" \
