refactor: install git dependency in a function (#557)

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -142,6 +142,37 @@ install_runtime_dependencies_aptget() {
   fi
 }
 
+install_runtime_dependencies_darwin() {
+  if ! command -v git > /dev/null 2>&1; then
+    printf '%s\n%s' "not found." "Installing git via the Xcode Command Line Tools... "
+    # These steps were taken from: https github com/Homebrew/install/blob/aceed88a4a062e2b41dc40a7428c71309fce14c9/install.sh#L831
+    # TODO: find a way to install only the git binary, not all the Xcode tools. Unattended git installation shouldn't take 20+ lines of code.
+    sudo touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+    clt_label_command="/usr/sbin/softwareupdate -l | grep -B 1 -E 'Command Line Tools' | awk -F'*' '/^ *\\*/ {print \$2}' | sed -e 's/^ *Label: //' -e 's/^ *//' | sort -V | tail -n1 | tr -d '\n'"
+    clt_label="$(/bin/sh -c "${clt_label_command}")"
+    if [ -n "${clt_label}" ]; then
+      sudo /usr/sbin/softwareupdate -i "${clt_label}" > /dev/null
+    else
+      handle_error "Failed to install git. Cannot find a compatible Xcode Command Line Tools package."
+    fi
+    sudo rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+
+    if command -v git > /dev/null 2>&1; then
+      printf '%s\n' "ok."
+    elif [ "${unattended}" = true ]; then
+      handle_error "Failed to install Xcode Command Line Tools. Try re-running without -u/--unattended or manually installing git."
+    else
+      printf '%s\n%s\n' "failed." "Installing the Command Line Tools (expect a popup window)."
+      /usr/bin/xcode-select --install
+      printf '%s\n' "PRESS ENTER after you've completed the installation via the popup window."
+      read -r _
+      if ! command -v git > /dev/null 2>&1; then
+        handle_error "Failed to install git via the Xcode Command Line Tools. Try manually installing git"
+      fi
+    fi
+  fi
+}
+
 install_runtime_dependencies_dnf() {
   dependencies_url="https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies/runtime_dependencies_dnf.txt"
   dependencies=$(curl --fail --silent --show-error --location --retry 5 --retry-delay 10 "${dependencies_url}")
@@ -486,6 +517,9 @@ Darwin)
     handle_error "Check for active internet failed."
   printf '%s\n' "ok."
   display_macos_warning
+  printf '%s\n%s' "ok." "Checking for git... "
+  install_runtime_dependencies_darwin
+  printf '%s\n' "ok."
   if ! command -v git > /dev/null 2>&1; then
     printf '%s' "Installing git via the Xcode Command Line Tools... "
     # These steps were taken from https://github.com/Homebrew/install/blob/aceed88a4a062e2b41dc40a7428c71309fce14c9/install.sh#L831
