Lots of updates and refactoring

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -47,8 +47,33 @@ get_os_release_type() (
   fi
 )
 
-install_dependencies() {
+install_build_dependencies_apk() {
+  apk --quiet add alpine-sdk libffi-dev autoconf automake db-dev boost boost-dev libtool libevent-dev |
+    grep -v "ICU with non-English locales" -A2 -B1 || true 
+}
+
+install_build_dependencies_aptget() {
+  DEBIAN_FRONTEND=noninteractive sudo apt-get -qq install --assume-yes --no-install-recommends build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev libsqlite3-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev > /dev/null
+}
+
+install_build_dependencies_dnf() {
+  sudo dnf install gcc-c++ libtool make autoconf automake python3 libevent-devel boost-devel sqlite-devel qt5-qttools-devel qt5-qtbase-devel qt5-qtwayland qrencode-devel
+}
+
+install_build_dependencies_pacman() {
+  echo "TODO: install_build_dependencies_pacman()"
+}
+
+install_build_dependencies_zypper() {
+  echo "TODO: install_build_dependencies_zypper()"
+}
+
+
+install_runtime_dependencies() {
   stderr_install_log_file="${temp_directory}/stderr_install.log"
+  dependencies_url="https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt"
+  dependencies=$(curl --fail --silent --show-error --location --retry 5 --retry-delay 10 "${dependencies_url}")
+  [ -z "${dependencies}" ] && handle_error "The list of dependencies is empty."
   printf '%s\n' "${dependencies}" | xargs sudo "$@" 2> "${stderr_install_log_file}"
   grep -v \
     -e "apt-utils" \
@@ -57,25 +82,25 @@ install_dependencies() {
   rm "${stderr_install_log_file}"
 }
 
-install_dependencies_aptget() {
+install_runtime_dependencies_aptget() {
   check_dpkg_lock
-  install_dependencies DEBIAN_FRONTEND=noninteractive apt-get -qq install --assume-yes --no-install-recommends > /dev/null
+  install_runtime_dependencies DEBIAN_FRONTEND=noninteractive apt-get -qq install --assume-yes --no-install-recommends > /dev/null
 }
 
-install_dependencies_dnf() {
-  install_dependencies dnf --assumeyes --quiet install > /dev/null
+install_runtime_dependencies_dnf() {
+  install_runtime_dependencies dnf --assumeyes --quiet install > /dev/null
 }
 
-install_dependencies_apk() {
-  install_dependencies apk --quiet add
+install__apk() {
+  install_ apk --quiet add
 }
 
-install_dependencies_pacman() {
-  install_dependencies pacman -Syu --needed --noconfirm --quiet > dev/null
+install_runtime_dependencies_pacman() {
+  install_runtime_dependencies pacman -Syu --needed --noconfirm --quiet > dev/null
 }
 
-install_dependencies_zypper() {
-  install_dependencies zypper --non-interactive --quiet install > /dev/null
+install_runtime_dependencies_zypper() {
+  install_runtime_dependencies zypper --non-interactive --quiet install > /dev/null
 }
 
 install_updates_aptget() {
@@ -265,7 +290,7 @@ Linux)
   debian | ubuntu)
     install_updates_aptget
     ;;
-  fedora | rhel)
+  fedora | rhel | centos*)
     install_updates_dnf
     ;;
   arch | manjaro)
@@ -309,27 +334,24 @@ Linux)
   printf '%s\n' "ok."
 
   printf '%s' "Checking for dependencies... "
-  dependencies_url="https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt"
-  dependencies=$(curl --fail --silent --show-error --location --retry 5 --retry-delay 10 "${dependencies_url}")
-  [ -z "$dependencies" ] && handle_error "The list of dependencies is empty."
   case "$(get_os_release_type)" in
   alpine)
-    install_dependencies_apk
+    install_runtime_dependencies_apk
     ;;
   debian | ubuntu)
-    install_dependencies_aptget
+    install_runtime_dependencies_aptget
     ;;
   fedora | rhel)
-    install_dependencies_dnf
+    install_runtime_dependencies_dnf
     ;;
   arch | manjaro)
-    install_dependencies_pacman
+    install_runtime_dependencies_pacman
     ;;
   suse | *opensuse*)
-    install_dependencies_zypper
+    install_runtime_dependencies_zypper
     ;;
   *)
-    install_command_function=""
+    install_runtime_command_function=""
     for package_manager in \
       apk \
       apt-get \
@@ -337,13 +359,13 @@ Linux)
       pacman \
       zypper; do
       if command -v "${package_manager}" > /dev/null; then
-        install_command_function="install_dependencies_$(echo "${package_manager}" | tr -d '-')"
+        install_runtime_command_function="install_runtime_dependencies_$(echo "${package_manager}" | tr -d '-')"
         break
       fi
     done
 
-    if [ -n "${install_command_function}" ]; then
-      "${install_command_function}"
+    if [ -n "${install_runtime_command_function}" ]; then
+      "${install_runtime_command_function}"
     else
       handle_error "This version of Linux is not supported."
     fi
@@ -427,30 +449,26 @@ elif [ "${compile_bitcoin:-"false"}" = "true" ] || [ "$(get_os_release_type)" = 
   printf '%s\n  %s' "not found." "Installing build dependencies... "
   case "$(get_os_release_type)" in
   alpine)
-    echo "install_build_dependencies_apk()"
-    apk --quiet add alpine-sdk libffi-dev autoconf automake db-dev boost boost-dev libtool libevent-dev |
-      grep -v "ICU with non-English locales" -A2 -B1 || true
+    install_build_dependencies_apk
     ;;
   debian | ubuntu)
-    echo "install_build_dependencies_aptget()"
-    DEBIAN_FRONTEND=noninteractive sudo apt-get -qq install --assume-yes --no-install-recommends build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev libsqlite3-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev > /dev/null
+    install_build_dependencies_aptget
     ;;
-  fedora | rhel)
-    echo "install_build_dependencies_dnf()"
-    sudo dnf install gcc-c++ libtool make autoconf automake python3 libevent-devel boost-devel sqlite-devel qt5-qttools-devel qt5-qtbase-devel qt5-qtwayland qrencode-devel
+  fedora | rhel | centos*)
+    install_build_dependencies_dnf
     ;;
   arch | manjaro)
-    echo "install_build_dependencies_pacman()"
+    install_build_dependencies_pacman
     ;;
   suse | *opensuse*)
-    echo "install_build_dependencies_zypper()"
+    install_build_dependencies_zypper
     ;;
   Darwin)
     sudo printf '' && NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &> /dev/null
     brew install --quiet automake boost libevent libtool pkg-config python qrencode qt@5 > /dev/null
     ;;
   *)
-    install_command_function=""
+    install_build_command_function=""
     for package_manager in \
       apk \
       apt-get \
@@ -462,12 +480,12 @@ elif [ "${compile_bitcoin:-"false"}" = "true" ] || [ "$(get_os_release_type)" = 
         break
       fi
     done
-    #if [ -n "${install_build_command_function}" ]; then
-    #  "${install_command_function}"
-    #else
-    #  handle_error "This version of Linux is not supported."
-    #fi
-    echo "DEBUG ONLY The build build command function to be called is ${install_build_command_function}()"
+    if [ -n "${install_build_command_function}" ]; then
+      echo "DEBUG: The build build command function to be called is ${install_build_command_function}()"
+      "${install_build_command_function}"
+    else
+      printf '%s\n  %s\n "failed." "Unable to determine build dependencies. Attempting to compile anyways."
+    fi
     ;;
   esac
   printf '%s\n  %s' "ok." "Downloading Bitcoin source code... "
@@ -480,6 +498,7 @@ elif [ "${compile_bitcoin:-"false"}" = "true" ] || [ "$(get_os_release_type)" = 
   ./configure --without-bdb --enable-suppress-external-warnings > /dev/null 2> "${stderr_compile_log_file}"
   grep -v \
     -e "libzmq" \
+    -e "xgettext" \
     "${stderr_compile_log_file}" >&2 || true
   printf '%s\n  %s' "ok." "Building (please wait)... "
   if [ "$(get_os_release_type)" = "Darwin" ]; then
