feat(ui): when printing errors, only print newline if needed (#607)
* feat(ui): add a get cursor column function

* feat(ui): print error messages on column 1

* fix syntax

* Avoid echo usage and unset unused variable

* fix typo with variable name

* Use a throwaway variable for the cursor’s row

* add test function

* fix whitespace

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -71,6 +71,33 @@ ensure_curl_dependency() {
   fi
 }
 
+get_cursor_column() {
+  stored_stty_settings=$(stty -g)
+  # Set raw mode, no echo, immediate read
+  stty raw -echo min 0 time 10
+  # Send ANSII escape code to request cursor position
+  printf "\033[6n" > /dev/tty
+  # System will print the cursor's row and column
+  IFS=';' read -r _ stty_column
+  stty "$stored_stty_settings"
+  printf '%s' "$stty_column"
+}
+
+test_get_cursor_column() {
+  # Test when cursor is at the start of a line
+  printf '\n'
+  col=$(find_cursor_column)
+  [ "$col" -ne 1 ] && throw_error "Failed: Expected 1, got $col"
+
+  # Test when cursor is at the end of the string "test"
+  printf '\n%s' "test"
+  col=$(find_cursor_column)
+  [ "$col" -ne 5 ] && throw_error "Failed: Expected 5, got $col"
+
+  printf '%s\n' "All tests passed"
+  return 0
+}
+
 get_free_space_in_mib() {
   if [ "$(uname -s)" = "Darwin" ]; then
     /bin/df -m "${HOME}" | awk '{print $4}' | sed 1d
@@ -296,7 +323,9 @@ is_valid_bitcoin_version() {
 }
 
 log_error() {
-  printf '\n%s\n' "[$(date +'%Y-%m-%dT%H:%M:%S')] ERROR: $*" >&2
+  test_get_cursor_column
+  [ "$(get_cursor_column)" -gt 0 ] && printf '\n'
+  printf '%s\n' "[$(date +'%Y-%m-%dT%H:%M:%S')] ERROR: $*" >&2
 }
 
 print_usage() {
