refactor handle exit logic

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -313,13 +313,6 @@ get_operating_system() {
 }
 
 # shellcheck disable=SC2317
-handle_error() {
-  log_error "Failed to run line $1."
-  handle_exit
-  exit 1
-}
-
-# shellcheck disable=SC2317
 handle_exit() {
   [ -n "${TEMP_DIRECTORY:-}" ] && rm -rf -- "${TEMP_DIRECTORY:?}"/
 }
@@ -743,31 +736,24 @@ set_bitcoin_core_option() {
 set_if_unset_bitcoin_core_option() {
   option="$1"
   value="$2"
-  [ ! -f "${bitcoin_core_config_file:?}" ] &&
+  # create a blank config file if it doesn't exist
+  if [ -f "${bitcoin_core_config_file:?}" ]; then
     install -m 600 /dev/null "${bitcoin_core_config_file:?}"
+  # add the new option if not already set
   grep -q -i "^${option}=" "${bitcoin_core_config_file:?}" ||
     printf '%s\n' "${option}=${value}" >> "${bitcoin_core_config_file:?}"
 }
 
 throw_error() {
-  if [ $# -gt 1 ]; then
-    log_error "$@"
-  elif [ $# -eq 1 ]; then
+  if [ $# -eq 1 ]; then
     log_error "$1"
+  elif [ $# -gt 1 ]; then
+    log_error "$@"
   else
-    log_error "Unknown error thrown at line ${LINENO:-}"
+    log_error "Unknown error thrown."
   fi
   handle_exit
   exit 1
-}
-
-# shellcheck disable=SC2317
-trap_exit_handler() {
-  if [ $? -eq 0 ]; then
-    handle_exit
-  else
-    handle_error "${LINENO:-}"
-  fi
 }
 
 # This list excludes vulnerable versions, e.g. CVE-2015-6031 and CVE-2018-17144
@@ -836,7 +822,7 @@ done
 
 [ "${unit_tests}" = 'true' ] && run_unit_tests
 
-trap trap_exit_handler EXIT
+trap 'if [ $? -eq 0 ]; then handle_exit; else throw_error "Unhandled error at line ${LINENO:-}."; fi' EXIT
 trap handle_sigint INT
 
 readonly BYTES_TO_KIB=1024
