feat(portability): add support and Dockerfile for Gentoo (#842)

diff --git a/nodebuilder b/nodebuilder
--- a/nodebuilder
+++ b/nodebuilder
@@ -57,6 +57,9 @@ ensure_curl_dependency() {
     fedora* | rhel | centos* | rocky | ol)
       sudo dnf install --allowerasing --assumeyes curl > /dev/null
       ;;
+    gentoo)
+      emerge --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail net-misc/curl
+      ;;
     arch | endeavouros | garuda | manjaro)
       sudo pacman -Syu --needed --noconfirm curl > /dev/null
       ;;
@@ -99,6 +102,10 @@ ensure_sudo_dependency() {
       ;;
     fedora* | rhel | centos* | rocky | ol)
       dnf install --allowerasing --assumeyes sudo > /dev/null
+      ;;
+    gentoo)
+      emerge --sync --quiet
+      emerge --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail app-admin/sudo
       ;;
     arch | endeavouros | garuda | manjaro)
       pacman -Syu --needed --noconfirm sudo > /dev/null
@@ -247,6 +254,23 @@ install_build_dependencies_dnf() {
   printf '%s\n' "${dependencies}" | xargs sudo dnf install --assumeyes > /dev/null
 }
 
+install_build_dependencies_emerge() {
+  readonly BUILD_DEPENDENCIES_URL='https://github.com/bitcoin-tools/nodebuilder/raw/841-feat-add-support-and-dockerfile-for-gentoo-linux/resources/dependencies/build_dependencies_emerge.txt'
+  printf '\n'
+  command -v torsocks > /dev/null 2>&1 &&
+    dependencies=$(torsocks curl --fail --silent --show-error --location --retry 2 "${BUILD_DEPENDENCIES_URL}") ||
+    dependencies=$(curl --fail --silent --show-error --location --retry 5 "${BUILD_DEPENDENCIES_URL}")
+  [ -z "${dependencies:-}" ] && throw_error 'The list of dependencies is empty.'
+  if ! printf '%s\n' "${dependencies}" | xargs emerge --autounmask-write \
+    --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail; then
+    etc-update --automode -5
+    emerge --update --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail --deep --newuse @world
+    # Run the install command again
+    printf '%s\n' "${dependencies}" | xargs emerge --autounmask-write \
+      --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail
+  fi
+}
+
 install_build_dependencies_pacman() {
   readonly BUILD_DEPENDENCIES_URL='https://github.com/bitcoin-tools/nodebuilder/raw/master/resources/dependencies/build_dependencies_pacman.txt'
   command -v torsocks > /dev/null 2>&1 &&
@@ -336,6 +360,16 @@ install_runtime_dependencies_dnf() {
   printf '%s\n' "${dependencies}" | xargs sudo dnf --assumeyes --quiet install > /dev/null
 }
 
+install_runtime_dependencies_emerge() {
+  readonly RUNTIME_DEPENDENCIES_URL='https://github.com/bitcoin-tools/nodebuilder/raw/841-feat-add-support-and-dockerfile-for-gentoo-linux/resources/dependencies/runtime_dependencies_emerge.txt'
+  printf '\n'
+  command -v torsocks > /dev/null 2>&1 &&
+    dependencies=$(torsocks curl --fail --silent --show-error --location --retry 2 "${RUNTIME_DEPENDENCIES_URL}") ||
+    dependencies=$(curl --fail --silent --show-error --location --retry 5 "${RUNTIME_DEPENDENCIES_URL}")
+  [ -z "${dependencies}" ] && throw_error 'The list of dependencies is empty.'
+  printf '%s\n' "${dependencies}" | xargs emerge --autounmask-write --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail
+}
+
 install_runtime_dependencies_pacman() {
   readonly RUNTIME_DEPENDENCIES_URL='https://github.com/bitcoin-tools/nodebuilder/raw/master/resources/dependencies/runtime_dependencies_pacman.txt'
   readonly STDERR_DEPENDENCIES_LOG_FILE="${TEMP_DIRECTORY}/stderr_runtime_dependencies_log"
@@ -380,6 +414,15 @@ install_system_updates_aptget() {
 
 install_system_updates_dnf() {
   sudo dnf clean all && sudo dnf --assumeyes --quiet upgrade > /dev/null
+}
+
+install_system_updates_emerge() {
+  readonly GENTOO_EBUILD_REPOSITORY='/var/db/repos/gentoo'
+  printf '\n'
+  [ -d "${GENTOO_EBUILD_REPOSITORY}" ] || mkdir -p "${GENTOO_EBUILD_REPOSITORY}"
+  emerge --depclean --quiet
+  emerge --update --jobs "$(nproc)" --load-average "$(($(nproc) + 1))" --quiet --quiet-build --quiet-fail --deep --newuse @world
+  emerge --depclean --quiet
 }
 
 install_system_updates_pacman() {
@@ -603,6 +646,9 @@ Linux)
   fedora* | rhel | centos* | rocky | ol)
     install_system_updates_dnf
     ;;
+  gentoo)
+    install_system_updates_emerge
+    ;;
   arch | endeavouros | garuda | manjaro)
     install_system_updates_pacman
     ;;
@@ -619,6 +665,8 @@ Linux)
       install_system_updates_aptget
     elif command -v dnf > /dev/null; then
       install_system_updates_dnf
+    elif command -v emerge > /dev/null; then
+      install_system_updates_emerge
     elif command -v pacman > /dev/null; then
       install_system_updates_pacman
     elif command -v swupd > /dve/null; then
@@ -658,6 +706,9 @@ Linux)
   fedora* | rhel | centos* | rocky | ol)
     install_runtime_dependencies_dnf
     ;;
+  gentoo)
+    install_runtime_dependencies_emerge
+    ;;
   arch | endeavouros | garuda | manjaro)
     install_runtime_dependencies_pacman
     ;;
@@ -673,6 +724,7 @@ Linux)
       apk \
       apt-get \
       dnf \
+      emerge \
       pacman \
       swupd \
       zypper; do
@@ -742,7 +794,9 @@ esac
 
 if [ "${current_bitcoin_version_padded}" = "${target_bitcoin_version_padded}" ]; then
   printf '%s\n' 'ok.'
-elif [ "${compile_bitcoin:-false}" = 'true' ] || [ "${TARGET_OPERATING_SYSTEM}" = 'alpine' ]; then
+elif [ "${compile_bitcoin:-false}" = 'true' ] ||
+  [ "${TARGET_OPERATING_SYSTEM}" = 'alpine' ] ||
+  [ "${TARGET_OPERATING_SYSTEM}" = 'gentoo' ]; then
   printf '%s\n  %s' 'no.' 'Ensuring compile dependencies... '
   readonly COMPILE_DIRECTORY="${TEMP_DIRECTORY}/compile_bitcoin"
   readonly STDERR_COMPILE_LOG_FILE="${TEMP_DIRECTORY}/stderr_install.log"
@@ -755,6 +809,9 @@ elif [ "${compile_bitcoin:-false}" = 'true' ] || [ "${TARGET_OPERATING_SYSTEM}" 
     ;;
   fedora* | rhel | centos* | rocky | ol)
     install_build_dependencies_dnf
+    ;;
+  gentoo)
+    install_build_dependencies_emerge
     ;;
   arch | endeavouros | garuda | manjaro)
     install_build_dependencies_pacman
@@ -774,6 +831,7 @@ elif [ "${compile_bitcoin:-false}" = 'true' ] || [ "${TARGET_OPERATING_SYSTEM}" 
       apk \
       apt-get \
       dnf \
+      emerge \
       pacman \
       swupd \
       zypper; do
