feat(portability): add support for NetBSD (#1401)

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -324,6 +324,43 @@ jobs:
           name: freebsd-source-bitcoin-debug.log
           path: /home/runner/work/nodebuilder/nodebuilder/debug.log
 
+  run-nodebuilder-netbsd:
+    name: Test source on NetBSD
+    needs: [changes, shell-lint, yaml-lint]
+    if: >-
+      ${{
+        github.event.action == 'prerelease' ||
+        github.event.action == 'published' ||
+        needs.changes.outputs.ci == 'true' ||
+        needs.changes.outputs.dependencies == 'true' ||
+        needs.changes.outputs.shell == 'true'
+      }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Test the console output
+        uses: vmactions/netbsd-vm@v1
+        timeout-minutes: 180
+        with:
+          prepare: |
+            echo "${TERM:-TERM is not found}"
+            uname -a
+            sysctl -n hw.ncpu
+            sysctl -n hw.physmem64
+            swapctl -l
+            df -h
+            date -u
+          run: |
+            sh -x ./nodebuilder
+            [ "$?" -gt 0 ] && echo "test_nodebuilder exited with status $?" >&2 && exit 1
+            [ -f "/home/bitcoin/.bitcoin/debug.log" ] && cp "/home/bitcoin/.bitcoin/debug.log" .
+            find / -name debug.log 2> /dev/null | grep bitcoin || true
+      - name: Save Bitcoin Core log as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: netbsd-source-bitcoin-debug.log
+          path: /home/runner/work/nodebuilder/nodebuilder/debug.log
+
   run-nodebuilder-openbsd:
     name: Test source on OpenBSD
     needs: [changes, shell-lint, yaml-lint]
