feat(portability): add support for OpenBSD (#1392)

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -309,6 +309,10 @@ jobs:
             nproc
             sysctl -a | grep ' memory' | head -2
             df -h
+            df
+            echo "${TERM:-TERM is not found}"
+            commmand -v tput
+            tput colors
             date -u
           run: |
             sh -x ./test/test_nodebuilder --ref "${GITHUB_SHA}"
@@ -318,6 +322,45 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: freebsd-source-bitcoin-debug.log
+          path: /home/runner/work/nodebuilder/nodebuilder/debug.log
+
+  run-nodebuilder-openbsd:
+    name: Test source on OpenBSD
+    needs: [changes, shell-lint, yaml-lint]
+    if: >-
+      ${{
+        github.event.action == 'prerelease' ||
+        github.event.action == 'published' ||
+        needs.changes.outputs.ci == 'true' ||
+        needs.changes.outputs.dependencies == 'true' ||
+        needs.changes.outputs.shell == 'true'
+      }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Test the console output
+        uses: vmactions/openbsd-vm@v1
+        timeout-minutes: 180
+        with:
+          prepare: |
+            uname -a
+            sysctl hw.ncpu
+            sysctl -a | grep 'hw.physmem\|hw.usermem'
+            df -h
+            df
+            echo "${TERM:-TERM is not found}"
+            commmand -v tput
+            tput colors
+            date -u
+          run: |
+            sh -x ./test/test_nodebuilder --ref "${GITHUB_SHA}"
+            [ "$?" -gt 0 ] && echo "test_nodebuilder exited with status $?" >&2 && exit 1
+            [ -f "/home/bitcoin/.bitcoin/debug.log" ] && cp "/home/bitcoin/.bitcoin/debug.log" .
+            find / -name debug.log 2> /dev/null | grep bitcoin || true
+      - name: Save Bitcoin Core log as artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: openbsd-source-bitcoin-debug.log
           path: /home/runner/work/nodebuilder/nodebuilder/debug.log
 
   run-nodebuilder-docker:
